/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes2;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.lang.reflect.Type;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Random;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

public class App {

    public static void main(String[] args) {
        try {
            Gson gson = new Gson();
            FileReader jsonFile = new FileReader("app/src/main/java/quotes2/Countact.json");
            BookQuiry [] book = gson.fromJson(jsonFile, BookQuiry[].class);
            System.out.println(book.length);
            Random random = new Random();
            int randomNumber = random.nextInt(100-1) + 1;
            System.out.println(book[randomNumber]);
        }catch (FileNotFoundException e) {
            e.printStackTrace();
        }}
}